apiVersion: apps/v1
kind: Deployment
metadata:
  name: wdatofte
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wdatofte
  template:
    metadata:
      labels:
        app: wdatofte
    spec:
      containers:
      - image: okteto.dev/wdatofte:latest
        name: wdatofte
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "d9c91160-633a-4e42-9e78-abdbf930c3d2"
        - name: Vless_Path
          value: "/d9c91160-633a-4e42-9e78-abdbf930c3d2-vless"
        - name: Vmess_UUID
          value: "d9c91160-633a-4e42-9e78-abdbf930c3d2"
        - name: Vmess_Path
          value: "/629c4616-2d94-4b6c-8a69-0286ef146662-vmess"
        - name: Share_Path
          value: "$Share_Path"
